// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AboutMeSectionContactMe: typeof import('./src/components/AboutMeSectionContactMe.vue')['default']
    AboutMeSectionExperience: typeof import('./src/components/AboutMeSectionExperience.vue')['default']
    AboutMeSectionLayout: typeof import('./src/components/AboutMeSectionLayout.vue')['default']
    AboutMeSectionProjects: typeof import('./src/components/AboutMeSectionProjects.vue')['default']
    AboutMeSectionSelfIntroduction: typeof import('./src/components/AboutMeSectionSelfIntroduction.vue')['default']
    AboutMeSectionSkills: typeof import('./src/components/AboutMeSectionSkills.vue')['default']
    ButtonDarkMode: typeof import('./src/components/ButtonDarkMode.vue')['default']
    ButtonHamburger: typeof import('./src/components/ButtonHamburger.vue')['default']
    ButtonRotateIcon: typeof import('./src/components/ButtonRotateIcon.vue')['default']
    ButtonScrollDown: typeof import('./src/components/ButtonScrollDown.vue')['default']
    CardProject: typeof import('./src/components/CardProject.vue')['default']
    CardProjectLinkOverlay: typeof import('./src/components/CardProjectLinkOverlay.vue')['default']
    copy: typeof import('./src/components/Prose copy.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CoverBody: typeof import('./src/components/CoverBody.vue')['default']
    Emphasis: typeof import('./src/components/Emphasis.vue')['default']
    IsomorphicLink: typeof import('./src/components/IsomorphicLink.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    LinkIcon: typeof import('./src/components/LinkIcon.vue')['default']
    NavbarHamburger: typeof import('./src/components/NavbarHamburger.vue')['default']
    NavbarLink: typeof import('./src/components/NavbarLink.vue')['default']
    NavbarLogo: typeof import('./src/components/NavbarLogo.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    Prose: typeof import('./src/components/Prose.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMembers: typeof import('./src/components/TeamMembers.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TitleCategory: typeof import('./src/components/TitleCategory.vue')['default']
    TransitionUniversal: typeof import('./src/components/TransitionUniversal.vue')['default']
  }
}
